### ISSUE TITLE
Provide Bootstrap layout

### ISSUE THREAD

**Issue by Portugao** [Portugao/MUImage#116]
- [x] backend: selection of theme - normal or bootstrap
- [x] special folder for bootstrap templates
- [x] create templates
- [x] have to clear which templates we need
- [x] we have to design the templates, several edit templates missing

**Comment by Portugao** [comment]
@trichers
First work is done. Now your part to design the templates...

**Comment by Portugao** [comment]
@trichers
Repository is ready, only one small issue is left. So you could work on templates for first bootstrap layout.

**Comment by Portugao** [comment]
You have to set layout to bootstrap in the settings.

**Comment by Portugao** [comment]
@trichers
What about your work for the bootstrap layout?

**Comment by Portugao** [comment]
@trichers
Hi Thomas,
please tell me if you will do this work and when yes until which date!

**Comment by trichers** [comment]
@Portugao Sorry for answering so late. I have now a project, where I´ll use MUimage and in will build the templates you asked for. Hope to end the project in April.

**Comment by Portugao** [comment]
@trichers
That sounds very good.

**Comment by trichers** [comment]
Now I am starting to test the module and building the bootstrap templates

**Comment by Portugao** [comment]
:+1:

**Comment by trichers** [comment]
Nach der Installation habe ich aus dem Frontend heraus ein Album angelegt.
Titel
Beschreibung
Nur für Benutzer
Im Frontend nicht angeklickt

Nach dem Speichern erhalte ich folgende Fehlermeldung:
ERR (3): E_USER_ERROR: Smarty error: [in album/display.tpl line 22]: syntax error: unrecognized tag 'muimageBreadcrumb' (Smarty_Compiler.class.php, line 590) in Smarty.class.php Zeile 1094 
Ich nutze Zikula 1.3.10

**Comment by Portugao** [comment]
Hmmmm..ok...bin gerade in der Entwicklung....die fehlende Datei muss ich noch committen....mom
Skype geht jetzt nicht....

**Comment by Portugao** [comment]
Getan.
Nun müsste der Fehler weg sein.

**Comment by trichers** [comment]
Welche Datei wurde geändert?

**Comment by Portugao** [comment]
Hinzugefügt: Das Plugin 'function.muimageBreadcrumb.php.

**Comment by Portugao** [comment]
@trichers
Wir brauchen hier eine Lösung für Hochkantbilder.....wenn ich das richtig sehe, geht Bootstrap damit nicht von sich aus gut um?!

**Comment by Portugao** [comment]
Not ready yet-

**Comment by Portugao** [comment]
Seems to be complete.

**Comment by trichers** [comment]
I hope I will find these days time to test it!

**Comment by Portugao** [comment]
:+1:
