### ISSUE TITLE
Error on sub album title links

### ISSUE THREAD

**Issue by DDRJ** [Portugao/MUImage#125]
In sub albums when logged in you have a link with the title of the album next to the red editing pen - if you click the link to the album name the following error is returned:
PHP Fatal error:  Call to undefined function exif_read_data() in C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\modules\MUImage\lib\MUImage\Util\Image.php on line 30

**Comment by Portugao** [comment]
Is the exif extension enabled on your server?
Which php version?

**Comment by DDRJ** [comment]
Not sure about the exif extension I will have to check. PHP version is 5.4.37

**Comment by Portugao** [comment]
Ok. Normally it should be in 5.4.

**Comment by DDRJ** [comment]
My hosting company say:
"Thank you for your email. We're not familiar with this standard, do you
require
simple mime type support or some form of processing support?"

If its mime I can add this myself

**Comment by Portugao** [comment]
Ok. So i have to implement a request if this library is there.

**Comment by Portugao** [comment]
Should be fixed now.
Also #126
