### ISSUE TITLE
Error on Image title links

### ISSUE THREAD

**Issue by DDRJ** [Portugao/MUImage#126]
when clicking the image name on individual images the following error is returned:
PHP Fatal error:  Call to undefined function exif_read_data() in C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\modules\MUImage\lib\MUImage\Util\Image.php on line 30

**Comment by DDRJ** [comment]
Many thanks for the latest edition of MU Image. I tried to upgrade by over
writing the 1.2 files with the new 1.3 files but when I try to upgrade in
the modules section of my site I get the following error:


 An error was encountered while dropping the tables for the MUImage module.
 Security token validation failed


Regards
David

**Comment by Portugao** [comment]
Plesse try to delete all files on the server and upload the new files.
Samstag, 19 März 2016, 11:32vorm. +0100 von DDRJ < notifications@github.com> :

**Comment by Portugao** [comment]
@DDRJ 
Cannot reproduce this.

**Comment by DDRJ** [comment]
I have tried this but still the same error

**Comment by Portugao** [comment]
Like i said, i cannot reproduce. Do you can get more informations with the development mode activated?

**Comment by DDRJ** [comment]
Thanks for your time it is appreciated - how do I activate development
mode - 1.39

**Comment by Portugao** [comment]
Set it to 1 in htaccess file Samstag, 19 März 2016, 02:50nachm. +0100 von DDRJ < notifications@github.com> :

**Comment by DDRJ** [comment]
Well I tried a completely fresh instal - removed 1.2 completely including
DB tables. When I tried to install 1.3 I get the following returned:
Error on Somerset Rivers

    Could not load the 'extensions' module at 'initialise'.
    SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry
'muimage.ui_hooks.albums.display_view' for key 'myindex'

    Exception Trace
    #0 Exception thrown in
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\lib\vendor\Doctrine\Doctrine\Connection.php,
line 1082.
    #1
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\lib\vendor\Doctrine\Doctrine\Connection.php(1042):
Doctrine_Connection_Statement->execute(Array)
    #2
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\lib\vendor\Doctrine\Doctrine\Connection.php(687):
Doctrine_Connection->exec('INSERT INTO hoo...', Array)
    #3
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\lib\vendor\Doctrine\Doctrine\Connection\UnitOfWork.php(647):
Doctrine_Connection->insert(Object(Doctrine_Table), Array)
    #4
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\lib\vendor\Doctrine\Doctrine\Connection\UnitOfWork.php(571):
Doctrine_Connection_UnitOfWork->processSingleInsert(Object(Zikula_Doctrine_Model_HookSubscriber))
    #5
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\lib\vendor\Doctrine\Doctrine\Connection\UnitOfWork.php(81):
Doctrine_Connection_UnitOfWork->insert(Object(Zikula_Doctrine_Model_HookSubscriber))
    #6
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\lib\vendor\Doctrine\Doctrine\Record.php(1718):
Doctrine_Connection_UnitOfWork->saveGraph(Object(Zikula_Doctrine_Model_HookSubscriber))
    #7
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\lib\Zikula\HookManager\Storage\Doctrine.php(39):
Doctrine_Record->save()
    #8
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\lib\Zikula\HookManager.php(106):
Zikula_HookManager_Storage_Doctrine->registerSubscriber('MUImage',
NULL, 'subscriber.muim...', 'display_view', 'ui_hooks',
'muimage.ui_hook...')
    #9
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\lib\util\HookUtil.php(155):
Zikula_HookManager->registerSubscriberBundle(Object(Zikula_HookManager_SubscriberBundle))
    #10
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\modules\MUImage\lib\MUImage\Installer.php(113):
HookUtil::registerSubscriberBundles(Array)
    #11 [internal function]: MUImage_Installer->install()
    #12
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\system\Extensions\lib\Extensions\Api\Admin.php(893):
call_user_func(Array)
    #13 [internal function]: Extensions_Api_Admin->initialise(Array)
    #14
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\lib\util\ModUtil.php(1091):
call_user_func(Array, Array)
    #15
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\lib\util\ModUtil.php(1199):
ModUtil::exec('Extensions', 'admin', 'initialise', Array, true, NULL)
    #16
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\system\Extensions\lib\Extensions\Controller\Admin.php(611):
ModUtil::apiFunc('Extensions', 'admin', 'initialise', Array)
    #17 [internal function]: Extensions_Controller_Admin->initialise(Array)
    #18
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\lib\util\ModUtil.php(1091):
call_user_func(Array, Array)
    #19
C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\lib\util\ModUtil.php(1173):
ModUtil::exec('Extensions', 'admin', 'initialise', Array, false, NULL)
    #20 C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\index.php(78):
ModUtil::func('Extensions', 'admin', 'initialise', Array)
    #21 {main}

**Comment by Portugao** [comment]
Yes, if you do not uninstall the module there get entries left for the hook functionality. You have to delete them from the hook tables by yourself.

**Comment by DDRJ** [comment]
Okay - I established that version 1.3 installs okay but I need to upgrade
version 1.2 because I have imported a lot of images from mediashare so I
tried the upgrade once again in development mode and this is the error
message:

Doctrine Exception: Unknown database type longblob requested,
Doctrine\DBAL\Platforms\MySqlPlatform may not support it.An error was
encountered while dropping the tables for the MUImage module.

**Comment by Portugao** [comment]
Sorry, that is a little bit funny for me because i had the idea that there could be a longblob field in your database.
Doctrine 2 does not support this kind of fields. Which module does this field have?

**Comment by DDRJ** [comment]
Well I had the old Mediashare tables in the DB once removed that solved
the longblob. The next issue was:

Doctrine Exception: SQLSTATE[23000]: Integrity constraint violation: 1062
Duplicate entry 'xxxxxxxxx' for key 'UNIQ_BF1851402B36786B'
there were about 50 por so I had to manually change on the DB.

Now the current issue is :

HTTP Error 500.0 - Internal Server Error
C:\Program Files (x86)\Parallels\Plesk\Additional\PleskPHP54\php-cgi.exe -
The FastCGI process exceeded configured request timeout

I increased the time limit but no joy - the error is:

Detailed Error Information:
Module	   FastCgiModule
Notification	   ExecuteRequestHandler
Handler	   PHP-php
Error Code	   0x80070102
Requested URL	  
http://davidjury.co.uk:80/index.php?module=extensions&type=admin&func=upgrade&id=45&startnum=0&csrftoken=NTZlZWFiZTY4Yzc4YTAuMDY4MTk1MjQ6MDc4NGYwNmMyN2Q1NDJiMmRjNWQxZGQyMzAwYzAwYTA6MTQ1ODQ4MjE1MA==&letter=M
Physical Path	   C:\Inetpub\vhosts\davidjury.co.uk\httpdocs\index.php
Logon Method	   Anonymous
Logon User	   Anonymous

**Comment by Portugao** [comment]
Puh, an error i never saw before.
What kind of system do you use. Seems you use it on your computer?

**Comment by DDRJ** [comment]
No not on my computer it is a hosted service from ehosting.com

Windows .NET & MS SQL

**Comment by Portugao** [comment]
I have no idea at the moment, how to solve this issue; i'm not sure how far this is an issue of MUImage?!

**Comment by Portugao** [comment]
And sorry; i wrote wrong, the development mode you have to activate in the config.php.

**Comment by DDRJ** [comment]
Michael yes I found the development ,mode in the config yesterday. I will
have a word with my hosting company to see if they have any ideas or
solutions.

Would it work if I did a fresh install of 1.3 and then copied the data
from the 1.2 tables into the new 1.3 tables ?

**Comment by Portugao** [comment]
Good idea.
Sorry. I cannot say for sure, because i don't know what the reason for the issue is...

**Comment by DDRJ** [comment]
My hosting company say that the error is just a time out error and that
the upgrade script is taking too long to complete.

I had a look at the database and saw that when the script timed out the
muimage_album and the muimage_album_category tables had been upgraded but
the muimage_picture table had not been - this table has close to 20000
rows - could that be the reason for the failure to complete the upgrade
process ?

**Comment by Portugao** [comment]
I think so. What about to increase the time a little bit more? Montag, 21 März 2016, 05:44nachm. +0100 von DDRJ < notifications@github.com> :

**Comment by DDRJ** [comment]
The hosting company say they cannot increase the time out because it is a
global setting.

I note there is no import facility in 1.3 - so I cannot reimport the images.

I will try and see if I can move the data from the old tables to the new
ones but if that fails it looks as if I will have to stay with version 1.2

**Comment by DDRJ** [comment]
Okay :
1. I exported the data from the three 1.2 tables
2. I uninstalled the 1.2 module
3. I did a new install of 1.3
4. Imported the data from version 1.2 into the three new tables of 1.3

Everything appears fine in the backend - all albums and all pictures are
showing but I cannot get anything to appear in the frontend.

There is a column in the album list - Not in Frontend - each album has a
red cross in that column - is that correct ?

Would it be easier for you to look at the site if I give you the log in
details ?

davidjury.co.uk
user name: admin
password: BYRON123 (all caps)

Its just a test site

**Comment by DDRJ** [comment]
further to my previous note I can view albums in front end in normal mode
but not bootstrap

**Comment by Portugao** [comment]
I had a look.
If you use the bootstrap layout, you have to embed the library of bootstrap

**Comment by DDRJ** [comment]
thank you

How do I embed the library of bootstrap ?

**Comment by Portugao** [comment]
http://getbootstrap.com/getting-started/
