### ISSUE TITLE
Error under php 5.4 in templates where (parent) album is called?

### ISSUE THREAD

**Issue by Portugao** [Portugao/MUImage#130]
```
WARN (4): E_WARNING: file_put_contents(ztemp/doctrinemodels/MUImage_Entity_AlbumProxy.php): failed to open stream: Permission denied in /www/htdocs/w00b922d/Zikula/139_deutsch/plugins/Doctrine/lib/vendor/Doctrine/ORM/Proxy/ProxyFactory.php Zeile 155 
```

**Comment by cmfcmf** [comment]
I also sometimes have this error with my own not-MOST module. I would be glad if you found a solution.

**Comment by Portugao** [comment]
Very strange error. I hope to find the reason to.

**Comment by Portugao** [comment]
Deleting the file 'MUImage_Entity_AlbumProxy.php' in ztemp folder fixes the issue.
With a new calling for the same page in the module the file will be created again and the issue seems to be gone.
So i close it.
Feel free to reopen.
