### ISSUE TITLE
ZIP-Upload Angabe der ZIP-Größe falsch

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#133]
Wenn ich bei ZIP-Größe 2000 eingebe, dann wertet er das als 1,9 KB
gebe ich nichts ein ist ein beliebig großer Upload möglich (der Server bestimmt hier dann die Grenze per TIMEOUT)

**Comment by Portugao** [comment]
Nee, denn die Eingabe erfolgt in Byte, 1024 Byte sind 1 KB.
