### ISSUE TITLE
Problem with translation

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#137]
Im template: https://github.com/Portugao/MUImage/blob/master/templates/bootstrap/picture/include_displayItemListMany.tpl wird in Zeile 12 ein Gettext abgerufen ohne Inhalt. Ist der Besucher nicht angemeldet erscheint folgende Fehlermeldung im Quelltext:

Project-Id-Version: Zikula 1.x
Report-Msgid-Bugs-To: 
POT-Creation-Date: 2015-02-21 21:02+0000
PO-Revision-Date: 2015-02-22 14:35+0100
Last-Translator: 
Language-Team: 
Language: de
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Generator: Poedit 1.6.9

**Comment by Portugao** [comment]
@trichers 
Sollte gefixt sein; eine Rückmeldung wäre fein.

**Comment by trichers** [comment]
Jawohl, so funktioniert es!

**Comment by Portugao** [comment]
Fine! :+1:
