### ISSUE TITLE
Scribite CKEditor Plugin - no thumbnails

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#138]
Wenn ich das Plugin im CKEditor aktiviere, kann ich nur das Bild in Originalgröße in den Text einfügen. Kann man da auch Thumbnail und Preview-Größen einstellen, so wie es bei SimpleMedia ging?

**Comment by Portugao** [comment]
Nein, derzeit nicht.

**Comment by Portugao** [comment]
Is implemented now.
