### ISSUE TITLE
Password unverschlüsselt in der Datenbank

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#139]
Legt man ein neues Album an, wird das User-Passwort automatisch unverschlüsselt in der Datenbank gespeichert. Ist das noch so?

**Comment by Portugao** [comment]
Das war noch nie so. Nur wenn man ein Album passwort geschützt anlegt, dann wird das Passwort gespeichert.
Von der Logik her soll es so sein, dass bei passwortgeschützten Alben normale User und Gäste das Passwort eingeben können, um Zugriff zu erhalten.
Das Problem war damlas, dass das Passwort im Backend angezeigt wurde; das ist nicht mehr der Fall.
Siehe auch #118 .

**Comment by trichers** [comment]
ok
