### ISSUE TITLE
New Uploadhandler

### ISSUE THREAD

**Issue by Portugao** [Portugao/MUImage#141]
- [x] modvar to select upload handler
- [x] mod vars for 3 different file sizes
- [x] upload handler, so we can upload pictures by creating 3 sizes near original picture
- [x] method to create 3 files sizes for each existing picture for change to bootstrap layout and new upload handling

**Comment by Portugao** [comment]
@trichers
How the embedding of the different image files should be?

**Comment by trichers** [comment]
Im Admin-Bereich könnte der Webmaster die Größenangaben für thumbnail, preview, full festlegen.
Beim Upload wird das Originalbild hochgeladen und die Kopien in der jeweiligen Größe erstellt (wobei die Angaben der Breite und Höhe jeweils die Maximale ist und das Bild natürlich proportional angepasst wird).

In der Galerieansicht, werden die Thumbnails angezeigt, was besonders für die mobile Ansicht einen wichtigen Performance-Faktor ausmacht.
In einer Slideransicht könnten die Previews zum Zuge kommen und die Full werden für den Lightbox-Effekt gebraucht.

Besonders wenn die Bilder über ein Scribite-Plugin in einem der Editoren verfügbar gemacht werden, ist eine Wahl zwischen thumbnail und preview notwendig.
Die img-tags sollte man nicht per inline-style regeln, sondern standard-mässig mit der bootstrap-class "img-responsive" versehen werden.

**Comment by Portugao** [comment]
Adminbereich und Upload ist klar.
Galerie ist auch klar.

Zu Scribite:
Welche Einbindungen sollten denn für die thumbnails und previews möglich sein?

**Comment by Portugao** [comment]
@trichers ping

**Comment by trichers** [comment]
Mindestanforderung:
Thumbnails und Previews ohne Link mit class="img-responsive"
Thumbnails und Previews mit Link per Lightbox zum Full mit class="img-responsive"

Optional:
Thumbnails und Previews mit Link zum Album zum Full mit class="img-responsive"
Nur Link zum Album

**Comment by Portugao** [comment]
:+1:

**Comment by Portugao** [comment]
Complete.
