### ISSUE TITLE
Unteralben lassen sich nicht bearbeiten

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#144]
Habe ich ein Unteralbum erstellt, und bin in der Albumansicht (display), erscheint kein BEARBEITEN Link bzw. Button.

**Comment by Portugao** [comment]
Bekommst Du denn den Schalter 'Aktionen für dieses Album' angezeigt?

**Comment by Portugao** [comment]
Bist Du im Bootstrap Layout?

**Comment by trichers** [comment]
ich bin im Bootstrap-Layout und ich bin in der Admin-Gruppe von Zikula. "Aktionen für dieses Album" werden im Unteralbum (wurde von einem anderen Benutzer angelegt) nicht angezeigt.

**Comment by Portugao** [comment]
Ok.

**Comment by Portugao** [comment]
Ist der andere Benutzer Admin?

**Comment by trichers** [comment]
ja

**Comment by Portugao** [comment]
Hmmhmm....

**Comment by Portugao** [comment]
Eine Gruppe für gemeinsame Alben darf nicht gesetzt sein?!

**Comment by trichers** [comment]
Ich habe die Gruppe "Redaktion" in den Einstellungen gesetzt. Und der User ist auch Mitglied in dieser Gruppe. Als Admin sollte ich jederzeit alle Alben ändern können!?

Ich würde die Rechte alle über das Zikula-Rechte-System steuern und nicht in den MUImage-Einstellungen.

**Comment by Portugao** [comment]
Should be fixed.
