### ISSUE TITLE
Bootstrap Überlegungen

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#145]
Wird das Album auf Boostrap eingestellt, dann wird Bootstrap von MUImage geladen. Wie kann man klären, ob Bootstrap im Theme nicht schon geladen ist, um einen doppelten Aufruf zu vermeiden?

Für die Navigation der Alben wird die navbar von bootstrap verwendet. Da aber die navbar auch im Theme eingesetzt werden könnte, wirkt sich das Stylesheet von MUImage auch auf die navbar des Themes aus. 
Vorschlag: die Navbar von MUImage in einen div mit Id packen um dann im stylesheet genau adressieren zu können.

**Comment by Portugao** [comment]
Zur ersten Frage habe ich momentan keine Antwort....

Das mit dem div geht klar.

**Comment by rallek** [comment]
Sollte bootstrap nicht immer durch das Theme geladen werden?

**Comment by Portugao** [comment]
Guter Einwand. Es sollte klar sein, dass Bootstrap eingebunden sein muss, wenn das Layout auf Bootstrap geschaltet ist.

Die Einbindung kommentiere ich aus.
