### ISSUE TITLE
CKEditor Plugin zeigt alle Bilder, aller Alben

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#146]
Das Plugin listet in der Bilderansicht alle Bilder auf, die in allen Alben sind. Bei über 50 Bildern und mehr ist das nicht mehr richtig nutzbar. 

Gibt es die Möglichkeit ein Album zu wählen und dann die Bilder des Albums anzuzeigen? (wie es in Mediashare der Fall war)

**Comment by Portugao** [comment]
Implemented.
