### ISSUE TITLE
Bootstrap-Container nicht verschachteln

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#147]
Wenn das Bootstrap-Layout verwendet wird, muss davon ausgegangen werden, dass das Theme auf Bootstrap basiert. Dementsprechend ist zu erwarten, dass MUImage innerhalb eines Containers aufgerufen wird. Wird nun im MUImage template erneut ein Container aufgerufen, ragt das Layout aus dem Theme heraus. 

Bei Bootstrap heißt es dazu:
"Bootstrap benötigt ein Element, in dem Seiteninhalte und unser Raster-System verpackt sind. Du kannst dir einen von zwei Containern zur Verwendung in deinem Projekt aussuchen. Beachte, dass aufgrund von padding und mehr keiner der beiden Container verschachtelbar ist."

Deshalb den Bereich nur in Rows packen und dort die neue co-md- Logik aufrufen. Die container-class überall entfernen.

**Comment by Portugao** [comment]
Welches template?

**Comment by trichers** [comment]
\templates\bootstrap\album\display.tpl (1 hit)
	Line 8: <div class="container">
\templates\bootstrap\album\edit.tpl (1 hit)
	Line 22: <div class="z-frontendcontainer">
\templates\bootstrap\album\view.tpl (1 hit)
	Line 213:     <div class="container-fluid album-bootstrap-view">
\templates\bootstrap\external\album\find.tpl (1 hit)
	Line 74:                     <div id="muimageItemContainer">
\templates\bootstrap\external\album\select.tpl (1 hit)
	Line 6:     <div id="{$baseID}PreviewContainer">&nbsp;</div>
\templates\bootstrap\external\picture\find.tpl (1 hit)
	Line 59:                     <div id="muimageItemContainer">
\templates\bootstrap\external\picture\select.tpl (1 hit)
	Line 6:     <div id="{$baseID}PreviewContainer">&nbsp;</div>
\templates\bootstrap\picture\edit.tpl (1 hit)
	Line 23: <div class="z-frontendcontainer">
\templates\bootstrap\picture\editMulti.tpl (1 hit)
	Line 15: <div class="z-frontendcontainer">
\templates\bootstrap\picture\multiUpload.tpl (1 hit)
	Line 9: <div class="z-frontendcontainer">
\templates\bootstrap\picture\slideshow.tpl (1 hit)
	Line 30:         container: '#blueimp-gallery-carousel',
\templates\bootstrap\picture\zipUpload.tpl (1 hit)
	Line 9: <div class="z-frontendcontainer">
\templates\bootstrap\user\header.tpl (2 hits)
	Line 26:   	<div class="container">
	Line 58:   </div>

**Comment by Portugao** [comment]
Da sind auch Treffer bei, bei denen der Begriff 'container' nur ein Teilstring ist, sorry?
Bitte verwende die aktuelle Version zum Testen, danke!

**Comment by Portugao** [comment]
Habe einige Container divs vor 2 Wochen gelöscht....

**Comment by Portugao** [comment]
Bzw. im Sinne des Tickets editiert...

**Comment by Portugao** [comment]
Ist das noch relevant?
Wenn ja, welche templates?

**Comment by Portugao** [comment]
ping @trichers
