### ISSUE TITLE
CKEditor Plugin fügt nicht Thumbnail sondern Bildname ein.

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#151]
Wähle ich das Plugin im CKEditor und will ein Bild einfügen passiert folgendes:
Link zum Bild: Bildname wird eingefügt mit Link zum Bild (korrekt)
ID des Bildes: Bildname wird eingefügt mit Link zum Bild (nicht korrekt bzw. nicht nötig?)
Thumbnail des Bildes: Bildname wird eingefügt mit Link zum Bild (NICHT korrekt, da kein Bild zu sehen)
Vorschau des Bildes: Bildname wird eingefügt mit Link zum Bild (NICHT korrekt, da kein Bild zu sehen)
das Gleich bei Lightbox.

**Comment by Portugao** [comment]
Shorturl aktiviert?

**Comment by trichers** [comment]
sind nicht aktiviert, habe es auch mit shorturl probiert. Gleiches Problem. Es wird kein <img>-tag erstellt.

**Comment by Portugao** [comment]
HTML Einstellungen:
IMG Tag mit Parametern freigegeben?

HTML Purifier aktiv?

**Comment by trichers** [comment]
daran liegt es nicht. Bevor du das Update bei dem Plugin gemacht hast, hat es wunderbar funktioniert.

**Comment by Portugao** [comment]
OK. Danke.
Hoffe auf Zeit am Wochenende.

**Comment by Portugao** [comment]
@trichers 
Should be fixed...
