### ISSUE TITLE
Absprachen Zikula Camp

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#154]
- [x]  nicht im Frontend sichtbar -> Nicht für Gäste sichtbar
- [x] Ab dem Breadcrumb ist vermutlich ein fehlender DIV tag 
- [x] Album-Ansicht: Bootstrap-Icons zu groß, Text daneben fehlt ab und zu ein Leerzeichen
- [x] Bootstrap Icons und Titel zusammen fassen.
- [x] Obere Admin-Leiste nur bei Login sichtbar
- [x] Kategorisierung abschaltbar über Backend
- [x] Kategorisierung abschaltbar -> Umgang bei nicht vorhandener Kategorie und Aktivieren -> siehe https://github.com/Portugao/MUImage/issues/158
- [x] Darstellung der Alben wie hier (wäre SUPER SCHÖN):
http://www.foxtons.co.uk/search?location_ids=1001-29&property_id=946191&resource=thumbnails&search_form=map&search_type=LL&sold=1&submit_type=search
Mögliches Galerie-Script:
http://tympanus.net/Development/GammaGallery/

- [x] Album-Übersicht mit Slide-Container von unten usw (siehe www.ekeb.de/index.php)

- [x] Bildupload:
Titel - Pflicht
Text - muss nicht (in Darstellung über if-abfrage regeln)
- [x] Klärung -> see #159 
Zeige Titel WARUM
Zeige Beschreibung WAR

- [x]  In der Displayansicht ist der Link auf das Bild tot
- [x] Plugin erstes Album laden

Im Plugin-Finder bei der Bildansicht
- [x]  Reihenfolge: Erst Album wählen, dann das was mit dem Bild geschehen soll, dann Bild anklicken
- [x]  Sortier und Suchfunktion erstmal ausblenden

NiceToHave:
- [x] Nicht auf Global-Kategorie sondern eigenen Hauptstrang erstellen.
- [x] Unteralben nicht zulassen
- [x] Info-Blöcke blau etwas schmäler in der Höhe

**Comment by trichers** [comment]
Bildupload:
Titel - Pflicht
Text - muss nicht (in Darstellung über if-abfrage regeln)
Zeige Titel WARUM
Zeige Beschreibung WARUM

**Comment by trichers** [comment]
In der Listenansicht ist der Link auf das Bild tot
Im Plugin-Finder bei der Bildansicht
Reihenfolge: Erst Album wählen, dann das was mit dem Bild geschehen soll, dann Bild anklicken

**Comment by trichers** [comment]
Mögliches Galerie-Script:
http://tympanus.net/Development/GammaGallery/

**Comment by Portugao** [comment]
@trichers 

Der Fehler 
```
 In der Listenansicht ist der Link auf das Bild tot
```
bezieht sich doch auf die Ansicht eines Albums, oder?

**Comment by Portugao** [comment]
Damit in der Ansicht eines Albums der Klick auf ein Bild die Lightbox öffnet, musst Du
```
{include file="layout/bootstrapModal.tpl"}
```
direkt unterhalb des <body> tags im theme einbinden.
Bitte checken und eine Rückmeldung, ob es dann arbeitet wäre nett :smile: .

**Comment by Portugao** [comment]
Ach ja, natürlich muss das template in den entsprechenden Ordner kopiert werden; findest Du im Ordner 'Resources'.

**Comment by Portugao** [comment]
@trichers 
Bitte sag mir noch mal, in welchem template dieses Problem
```
 Ab dem Breadcrumb ist vermutlich ein fehlender DIV tag 
```
auftaucht.

**Comment by trichers** [comment]
In der &func=display&ot=album&id=1

**Comment by Portugao** [comment]
:ok_hand:
