### ISSUE TITLE
Aktionen für dieses Album für Admin nicht sichtbar

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#162]
Ich habe eine Gruppe (Redaktion) angelegt und in den Zugriffsrechten MUImage .* administrieren freigegeben. Leider wird das Pulldownmenü in der Album-Display-Ansicht nicht für die Benutzer dieser Gruppe angezeigt.

**Comment by Portugao** [comment]
Strange. I will see.

**Comment by Portugao** [comment]
Please set this group as group for common albums.
Du  musst die Gruppe 'Redaktion' als Gruppe für gemeinsame Alben setzen.

**Comment by trichers** [comment]
das war natürlich schon so eingestellt. Daran kann es also nicht gelegen haben.

**Comment by Portugao** [comment]
Ist denn der Ersteller des Albums auch der Gruppe 'Redaktion' zugewiesen?

**Comment by trichers** [comment]
Nein, der Ersteller ist Mitglied der Gruppe Administratoren.
Bei den Einstellungen zu den Zugriffsrechten sind zu MUImage folgende Eintragungen möglich:
MUImage:: 	::
MUImage:Album: 	AlbumID::
MUImage:Album:Album 	AlbumID:AlbumID:
MUImage:Album:Picture 	AlbumID:PictureID:
MUImage:ItemListBlock: 	BlockId::
MUImage:OneItemBlock: 	BlockId::
MUImage:Picture: 	PictureID::

Was muss ich eintragen, damit alle Mitglieder der Gruppe Redaktion Admin-Rechte über alle Alben erhalten, egal wer sie anlegt?

**Comment by Portugao** [comment]
Warum nicht? Dann wäre alles gut?!

**Comment by trichers** [comment]
Nein, wenn ich bei Projekten mehrere Gruppen einsetze, geht das ganze schon nicht mehr. Bei anderen Modulen wird das doch auch alles über das Rechtesystem von Zikula geregelt oder?

**Comment by Portugao** [comment]
Hmmhmm....über welches Recht, die zur verfügung stehen, möchtest Du das geregelt haben?

**Comment by trichers** [comment]
ich will einer Gruppe das Recht geben, alle Alben und Bilder, die egal von wem hochgeladen wurden zu administrieren.

**Comment by Portugao** [comment]
Also über

```
MUImage:: | .* | administrieren
```

**Comment by trichers** [comment]
ja

**Comment by Portugao** [comment]
Ok.

**Comment by trichers** [comment]
Super Danke!!

**Comment by Portugao** [comment]
Done!
Nur das template bootstrap/album/display.tpl ist geändert.
