### ISSUE TITLE
Scribite-Plugin - Einfügen Orginial-Bild

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#163]
Irgendwie haben wir übersehen, dass es noch hilfreich wäre, wenn man im Editor bei der Auswahl nicht nur Thumbnails und Previews, sondern auch das Bild in Originalgröße einfügen kann.

**Comment by Portugao** [comment]
Nicht die full Version, sondern das Originalbild; ist das richtig?

**Comment by trichers** [comment]
ja

**Comment by Portugao** [comment]
:+1: 
Baue ich ein.
