### ISSUE TITLE
Es fehlt immer noch ein </div> als Admin

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#164]
Bin ich als Admin angemeldet fehlt in dem Template templates/bootstrap/album/display.tpl immer noch ein schließender </div> - Tag.
Es ist zwar Kosmetik, aber es zerschießt mir die nachfolgenden Tags (wie z.B. den Footer)
Hab versucht den Fehler zu finden, komme aber nicht dahinter.

**Comment by Portugao** [comment]
Hast Du auch den aktuellen Stand?
Samstag, 31 Oktober 2015, 02:13nachm. +0100 von Thomas Richers < notifications@github.com> :

**Comment by Portugao** [comment]
Ok. Ich schau mir das noch mal an.

**Comment by Portugao** [comment]
@trichers 
Versuch bitte den aktuellen Stand! Danke.

**Comment by trichers** [comment]
Top, jetzt funktionierts! Danke!

**Comment by Portugao** [comment]
:+1:
