### ISSUE TITLE
Plugin CKEditor Fehler

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#165]
Beim Plugin zum einfügen von Bildern den CKEditor gibt es folgende Problemstellung:

Standardmässig werden 20 Bilder aufgerufen. Die Anzahl kann ich unterhalb über das Pulldown-Menü ändern. 
Habe ich zuvor aber ein Album gewählt und ändere dann die Anzahl der anzuzeigenden Bilder, dann werden zwar die gewünschte Anzahl der Bilder angezeigt, aber es springt wieder auf das erste Album.
So kann ich NIE mehr als 20 Bilder aus den weiteren Alben anzeigen und auswählen!

**Comment by Portugao** [comment]
Schaue ich mir an.

**Comment by Portugao** [comment]
@trichers 
Bitte mal checken!

**Comment by Portugao** [comment]
@trichers 
?

**Comment by Portugao** [comment]
@trichers 
Moin Thomas, eine Rückmeldung wäre mal schön.

**Comment by trichers** [comment]
Konnte es erst jetzt ausgiebig testen. Jetzt geht es! Danke

**Comment by Portugao** [comment]
Fein. Gerne!
