### ISSUE TITLE
Probleme beim Album wählen im Finder im CKEditor unter Chrome

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#168]
Wenn ich im CKEditor MUImage aufrufe, dann kann ich im PopUp-Fenster unter den verschiedenen Alben wählen. Das funktioniert im Firefox und IE, aber nicht unter Chrome.

**Comment by trichers** [comment]
Vielleicht hilft das:
http://stackoverflow.com/questions/20367046/onclick-event-firing-in-firefox-and-ie-but-not-in-chrome

**Comment by Portugao** [comment]
@trichers 
Should be fixed.
