### ISSUE TITLE
Wie kann ich ein Album über die URL nach Kategorie filtern

### ISSUE THREAD

**Issue by trichers** [Portugao/MUImage#169]

**Comment by Portugao** [comment]
?

**Comment by trichers** [comment]
Ich habe die Alben unterschiedlichen Kategorien zugeordnet. Wie kann ich jetzt alle Alben einer bestimmten Kategorie aufrufen?

**Comment by Portugao** [comment]
Puh.....derzeit keine Ahnung...

**Comment by Portugao** [comment]
Versuch mal den Parameter
catidMain=Kategorie ID

**Comment by Portugao** [comment]
Mit shorturls:
catidMain/KategorieId

**Comment by trichers** [comment]
Das klappt leider nicht.
Habe versucht: 
{MUImage:user:view:filter=catidMain^eq^10024}
daraus wurde
MUImage/view/albums/filter/catidMain^eq^10024

**Comment by Portugao** [comment]
{MUImage:user:view:catidMain=10024}
Schuss ins Blaue....

**Comment by Portugao** [comment]
@trichers 
Eine Rückmeldung wäre gut.
